---
apiVersion: v1
kind: Service
metadata:
  annotations:
    description: Flask App for Civis DEVELOP
    contact: Chris Perry
  labels:
    env: civis-develop
    name: flask-app-civis-develop
  name: flask-app-civis-develop
  namespace: civis-develop
spec:
  ports:
  - name: http
    targetPort: http
    port: 80
    protocol: TCP
  selector:
    name: flask-app-civis-develop
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: flask-app-ingress-civis-develop
  namespace: civis-develop
spec:
  # tls:
  # - secretName: tls
  backend:
    serviceName: flask-app-civis-develop
    servicePort: 80