---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: flask-app-civis-demo
  namespace: civis-demo
spec:
  scaleTargetRef:
    kind: Deployment
    name: flask-app-civis-demo
    namespace: civis-demo
  minReplicas: 1
  maxReplicas: 50
  targetCPUUtilizationPercentage: 50
