---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    description: Postgres data volume 1 for civis demo
  name: civis-postgres-cluster-data-1
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 15Gi
  storageClassName: standard
  gcePersistentDisk:
    pdName: civis-postgres-cluster-data-1
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    description: Postgres data volume 2 for civis demo
  name: civis-postgres-cluster-data-2
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 15Gi
  storageClassName: standard
  gcePersistentDisk:
    pdName: civis-postgres-cluster-data-2
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    description: Postgres data volume 3 for civis demo
  name: civis-postgres-cluster-data-3
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 15Gi
  storageClassName: standard
  gcePersistentDisk:
    pdName: civis-postgres-cluster-data-3
  persistentVolumeReclaimPolicy: Retain