---
apiVersion: v1
kind: Service
metadata:
  annotations:
    contact: Chris Perry
  labels:
    env: civis-demo
    name: civis-demo-postgres
  name: civis-demo-postgres
  namespace: civis-demo
spec:
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
    nodePort: 30433
  selector:
    name: civis-demo-postgres
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    contact: Chris Perry
  labels:
    app: civis-demo-redis
    role: master
    tier: backend
  name: civis-demo-redis
  namespace: civis-demo
spec:
  # clusterIP: 10.151.249.22
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: civis-demo-redis
    role: master
    tier: backend
  sessionAffinity: None
  type: ClusterIP
