# echo -n "Kh7FtUbC48qJ" | base64
---
kind: Secret
apiVersion: v1
metadata:
  name: dev-postgres
  namespace: civis-demo
type: Opaque
data:
  username: YXJhY2huaWQK
  password: ZGV2aW91czhvYjgK
---
kind: Secret
apiVersion: v1
metadata:
  name: civis-demo-secrets
  namespace: civis-demo
type: Opaque
data:
  db-user: Y2l2aXNfdXNlcl9kYl9hY2Nlc3M= #civis_user_db_access
  db-pass: Y2l2aXNfcGFzcw== #civis_pass